AWSTemplateFormatVersion: '2010-09-09'
Description: "CD Demo Lambda"
Resources: 
  CDDemoLambda: 
    Properties: 
      CodeUri: ./LAMBDA_SAM
      Description: "Lambda Function for cd demo"
      Environments: 
        Variables: 
          REGION: us-east-1
      Events: 
        getAZsAPI: 
          Properties: 
            Method: get
            Path: /getazs
          Type: Api
      Handler: Lambda_function.Lambda_handler
      MemorySize: 1024
      Role: "arn:aws:iam::437968510040:role/cfrole"
      Runtime: python3.6
      Timeout: 900
    Type: 'AWS::Serverless::Function'
Transform: AWS::Serverless-2016-10-31